jenkins:
  systemMessage: "Automated build system for Posit Package Manager package publishing\n\n"
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "admin"
          password: "admin"
credentials:
  system:
    domainCredentials:
      - credentials:
          - string:
              scope: GLOBAL
              id: "PACKAGEMANAGER_TOKEN"
              secret: "${PPM_TOKEN}"
              description: "API Token for Posit Package Manager"
          - basicSSHUserPrivateKey:
              description: "SSH Key for accessing Git Repositories"
              id: "GIT_SSH_KEY"
              privateKeySource:
                directEntry:
                  privateKey: "${GIT_SSH_KEY}"
              scope: GLOBAL
security:
  gitHostKeyVerificationConfiguration:
    sshHostKeyVerificationStrategy: "acceptFirstConnectionStrategy"
  globalJobDslSecurityConfiguration:
    useScriptSecurity: false
unclassified:
  location:
    url: http://localhost:8083/
